#include <iostream>
#include <math.h>
#include <conio.h>

using namespace std;

int main() {
	
	int num1;
	
			
	cout << "Introduzca el binario de alguno de estos numeros o letras " << endl;
	cout << " 0 = 0000" << endl;
	cout << " 1 = 0001" << endl;
	cout << " 2 = 0010" << endl;
	cout << " 3 = 0011" << endl;
	cout << " 4 = 0100" << endl;
	cout << " 5 = 0101" << endl;
	cout << " 6 = 0110" << endl;
	cout << " 7 = 0111" << endl;
	cout << " 8 = 1000" << endl;
	cout << " 9 = 1001" << endl;
	cout << " A = 1010" << endl;
	cout << " b = 1011" << endl;
	cout << " C = 1100" << endl;
	cout << " d = 1101" << endl;
	cout << " E = 1110" << endl;
	cout << " F = 1111" << endl;
	cout << "Convertir decimales a binario a hexadecimal" << endl;
	cin >> num1;

  if (num1 == 0000) {
      cout << " ";
      cout << "-";
      cout << " ";
      cout << endl;
      cout << "|";
      cout << " ";
      cout << "|";
      cout << endl;
      cout << "|";
      cout << " ";
      cout << "|";
      cout << endl;
      cout << " ";
      cout << "-";
      cout << " ";
      cout << endl;
  } else if (num1 == 0001) {
      cout << " ";
      cout << " ";
      cout << "|";
      cout << endl;
      cout << " ";
      cout << " ";
      cout << "|";
      cout << endl;
      cout << " ";
      cout << " ";
      cout << " ";
      cout << endl;
  } else if (num1 == 0010) {
      cout << " ";
      cout << "-";
      cout << " ";
      cout << endl;
      cout << " ";
      cout << " ";
      cout << "|";
      cout << endl;
      cout << " ";
      cout << "-";
      cout << " ";
      cout << endl;
	  cout << "|";
      cout << " ";
      cout << " ";
      cout << endl;
      cout << " ";
      cout << "-";
      cout << " ";
      cout << endl;
  } else if (num1 == 0011) {
      cout << " ";
      cout << "-";
      cout << " ";
      cout << endl;
      cout << " ";
      cout << " ";
      cout << "|";
      cout << endl;
      cout << " ";
      cout << "-";
      cout << " ";
      cout << endl;
      cout << " ";
      cout << " ";
      cout << "|";
      cout << endl;
      cout << " ";
      cout << "-";
      cout << " ";
      cout << endl;
  } else if (num1 == 0100) {
      cout << " ";
      cout << " ";
      cout << " ";
      cout << endl;
      cout << "|";
      cout << " ";
      cout << "|";
      cout << endl;
      cout << " ";
      cout << "-";
      cout << " ";
      cout << endl;
      cout << " ";
      cout << " ";
      cout << "|";
      cout << endl;
  } else if (num1 == 0101) {
      cout << " ";
      cout << "-";
      cout << " ";
      cout << endl;
      cout << "|";
      cout << " ";
      cout << " ";
      cout << endl;
      cout << " ";
      cout << "-";
      cout << " ";
      cout << endl;
      cout << " ";
      cout << " ";
      cout << "|";
      cout << endl;
      cout << " ";
      cout << "-";
      cout << " ";
      cout << endl;
  } else if (num1 == 0110) {
      cout << " ";
      cout << "-";
      cout << " ";
      cout << endl;
      cout << "|";
      cout << " ";
      cout << " ";
      cout << endl;
      cout << " ";
      cout << "-";
      cout << " ";
      cout << endl;
      cout << "|";
      cout << " ";
      cout << "|";
      cout << endl;
      cout << " ";
      cout << "-";
      cout << " ";
      cout << endl;
  } else if (num1 == 0111) {
      cout << " ";
      cout << "-";
      cout << " ";
      cout << endl;
      cout << " ";
      cout << " ";
      cout << "|";
      cout << endl;
      cout << " ";
      cout << "-";
      cout << " ";
      cout << endl;
      cout << " ";
      cout << " ";
      cout << "|";
      cout << endl;
  } else if (num1 == 1000) {
      cout << " ";
      cout << "-";
      cout << " ";
      cout << endl;
      cout << "|";
      cout << " ";
      cout << "|";
      cout << endl;
      cout << " ";
      cout << "-";
      cout << " ";
      cout << endl;
      cout << "|";
      cout << " ";
      cout << "|";
      cout << endl;
      cout << " ";
      cout << "-";
      cout << " ";
      cout << endl;
  } else if (num1 == 1001) {
      cout << " ";
      cout << "-";
      cout << " ";
      cout << endl;
      cout << "|";
      cout << " ";
      cout << "|";
      cout << endl;
      cout << " ";
      cout << "-";
      cout << " ";
      cout << endl;
      cout << " ";
      cout << " ";
      cout << "|";
      cout << endl;
      cout << " ";
      cout << "-";
      cout << " ";
      cout << endl;
  } else if (num1 == 1010) {
      cout << " ";
      cout << "-";
      cout << " ";
      cout << endl;
      cout << "|";
      cout << " ";
      cout << "|";
      cout << endl;
      cout << " ";
      cout << "-";
      cout << " ";
      cout << endl;
      cout << "|";
      cout << " ";
      cout << "|";
      cout << endl;
      cout << " ";
      cout << " ";
      cout << " ";
      cout << endl;
  } else if (num1 == 1011) {
      cout << " ";
      cout << " ";
      cout << " ";
      cout << endl;
      cout << "|";
      cout << " ";
      cout << " ";
      cout << endl;
      cout << " ";
      cout << "-";
      cout << " ";
      cout << endl;
      cout << "|";
      cout << " ";
      cout << "|";
      cout << endl;
      cout << " ";
      cout << "-";
      cout << " ";
      cout << endl;
  } else if (num1 == 1100) {
    cout << " ";
      cout << "-";
      cout << " ";
      cout << endl;
      cout << "|";
      cout << " ";
      cout << " ";
      cout << endl;
      cout << "|";
      cout << " ";
      cout << " ";
      cout << endl;
      cout << " ";
      cout << "-";
      cout << " ";
      cout << endl;
  } else if (num1 == 1101) {
      cout << " ";
      cout << " ";
      cout << " ";
      cout << endl;
      cout << " ";
      cout << " ";
      cout << "|";
      cout << endl;
      cout << " ";
      cout << "-";
      cout << " ";
      cout << endl;
      cout << "|";
      cout << " ";
      cout << "|";
      cout << endl;
      cout << " ";
      cout << "-";
      cout << " ";
      cout << endl;
  } else if (num1 == 1110) {
    cout << " ";
      cout << "-";
      cout << " ";
      cout << endl;
      cout << "|";
      cout << " ";
      cout << " ";
      cout << endl;
      cout << " ";
      cout << "-";
      cout << " ";
      cout << endl;
      cout << "|";
      cout << " ";
      cout << " ";
      cout << endl;
      cout << " ";
      cout << "-";
      cout << " ";
      cout << endl;
  } else if (num1 == 1111) {
    cout << " ";
      cout << "-";
      cout << " ";
      cout << endl;
      cout << "|";
      cout << " ";
      cout << " ";
      cout << endl;
      cout << " ";
      cout << "-";
      cout << " ";
      cout << endl;
      cout << "|";
      cout << " ";
      cout << " ";
      cout << endl;
      cout << " ";
      cout << " ";
      cout << " ";
      cout << endl;
  } else {
    cout << "Numero Invalido" << endl;
    

}
  
  return 0;
}
